-- V3: refresh-token persistence + account lockout fields
ALTER TABLE users ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN locked_until TIMESTAMP;
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP;

CREATE TABLE refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP,
    created_by   VARCHAR(64),
    updated_by   VARCHAR(64),
    token_hash   VARCHAR(128) NOT NULL UNIQUE,
    username     VARCHAR(64)  NOT NULL,
    issued_at    TIMESTAMP    NOT NULL,
    expires_at   TIMESTAMP    NOT NULL,
    revoked      BOOLEAN      NOT NULL DEFAULT FALSE,
    replaced_by  VARCHAR(128),
    user_agent   VARCHAR(255),
    ip_address   VARCHAR(64)
);

CREATE INDEX idx_refresh_tokens_username   ON refresh_tokens(username);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);
